"""Blind listening set for the TTS bake-off. Stdlib + ffmpeg only.

  python3 make_blind.py            build blind/ from out/*.wav plus anything in extra/
  python3 make_blind.py --force    rebuild with a new shuffle (ratings made on the old set no longer match)
  python3 make_blind.py --reveal   print which clip is which -- do this AFTER rating

Every clip is loudness-matched (two-pass EBU R128, -16 LUFS), downmixed to mono at one sample rate, stripped of metadata
and renamed clip-NN in a random order, because the loudest clip wins most listening tests regardless of quality.
The mapping goes to blind-key.json, outside blind/, so it is not sitting next to the files.

extra/ is for clips made elsewhere (e.g. one you generated by hand in Suno). Any audio file dropped there is
included. What cannot be blinded: clip length. The passage is fixed, so a faster engine is shorter.
"""
import json, pathlib, random, subprocess, sys
from common import HERE, OUT

BLIND = HERE / "blind"
KEY = HERE / "blind-key.json"
EXTRA = HERE / "extra"
AUDIO = {".wav", ".mp3", ".m4a", ".flac", ".ogg", ".aac"}


def sources():
    found = [(p, p.stem) for p in sorted(OUT.glob("*.wav"))]
    if EXTRA.is_dir():
        found += [(p, f"extra: {p.name}") for p in sorted(EXTRA.iterdir()) if p.suffix.lower() in AUDIO]
    return found


TARGET = "I=-16:TP=-1.5:LRA=11"


def normalize(src: pathlib.Path, dst: pathlib.Path):
    """Two-pass loudnorm. One pass undershoots on clips with long pauses (measured: ~2 LU quieter than the rest)."""
    first = subprocess.run(
        ["ffmpeg", "-nostats", "-i", str(src), "-vn", "-af", f"loudnorm={TARGET}:print_format=json", "-f", "null", "-"],
        capture_output=True, text=True, check=True,
    ).stderr
    m = json.loads(first[first.rindex("{"):first.rindex("}") + 1])
    measured = (f"measured_I={m['input_i']}:measured_TP={m['input_tp']}:measured_LRA={m['input_lra']}"
                f":measured_thresh={m['input_thresh']}:offset={m['target_offset']}:linear=true")
    subprocess.run(
        ["ffmpeg", "-v", "error", "-y", "-i", str(src), "-map_metadata", "-1", "-vn", "-af", f"loudnorm={TARGET}:{measured}",
         "-ac", "1", "-ar", "44100", "-c:a", "pcm_s16le", str(dst)],
        check=True,
    )


def build(force: bool):
    if BLIND.exists() and any(BLIND.iterdir()) and not force:
        sys.exit("blind/ already exists. Use --force to rebuild (this reshuffles, so earlier ratings stop matching).")
    src = sources()
    if not src:
        sys.exit("no clips found in out/ or extra/")
    if BLIND.exists():
        for old in BLIND.iterdir():
            old.unlink()
    BLIND.mkdir(exist_ok=True)

    order = list(range(len(src)))
    random.SystemRandom().shuffle(order)
    key = {}
    # Written in id order so file creation time carries no information either.
    for n, i in enumerate(order, start=1):
        path, label = src[i]
        clip = f"clip-{n:02d}"
        normalize(path, BLIND / f"{clip}.wav")
        key[clip] = {"source": path.name, "label": label}
    KEY.write_text(json.dumps(key, indent=1))
    KEY.chmod(0o600)
    (BLIND / "SCORECARD.md").write_text(scorecard(sorted(key)))
    print(f"built {len(key)} clips in {BLIND.relative_to(HERE)}/ (key saved to {KEY.name} -- don't open it until you have rated)")
    if not any(label.startswith("extra:") for _, label in src):
        print("no clip in extra/ yet -- add one (e.g. from Suno) and re-run with --force before you start listening")


def scorecard(clips):
    rows = "\n".join(f"| {c} |  |  |  |  |" for c in clips)
    return f"""# Blind scorecard

Same passage, every clip. Score 1-5 (5 best). Rate naturalness and clarity first, listen for the CVE id
("CVE-2024-3094"), then decide whether you could sit through nine minutes of it.

| clip | natural | clear | 9 min OK? (y/n) | notes |
|---|---|---|---|---|
{rows}

Then run `python3 make_blind.py --reveal`.
"""


def reveal():
    if not KEY.exists():
        sys.exit("no blind-key.json -- build the set first")
    for clip, v in sorted(json.loads(KEY.read_text()).items()):
        print(f"{clip}  {v['label']}")


if __name__ == "__main__":
    if "--reveal" in sys.argv:
        reveal()
    else:
        build("--force" in sys.argv)
